package org.example.comicsrest;

import lombok.RequiredArgsConstructor;
import org.example.comicsrest.database.entity.Comic;
import org.example.comicsrest.database.enums.Genres;
import org.example.comicsrest.database.repository.ComicRepository;
import org.example.comicsrest.security.pojo.Role;
import org.example.comicsrest.security.entity.User;
import org.example.comicsrest.security.enums.RoleType;
import org.example.comicsrest.security.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class ComicsRestApplication {

	private final ComicRepository comicRepository;
	private final UserRepository userRepository;
	private final PasswordEncoder passwordEncoder;

	@Autowired
	public ComicsRestApplication(ComicRepository comicRepository, UserRepository userRepository, PasswordEncoder passwordEncoder) {
		this.comicRepository = comicRepository;
		this.userRepository = userRepository;
		this.passwordEncoder = passwordEncoder;
	}

	@Bean @Profile("dev")
	public ApplicationRunner init() {
		return args -> {

			User dev = new User("dev","dev@gmail.com",passwordEncoder.encode("12345"));
			User admin = new User("admin","admin@gmail.com",passwordEncoder.encode("12345"));
			User normalUser = new User("john","John@gmail.com",passwordEncoder.encode("12345"));

			dev.addRole(new Role(RoleType.Dev));
			dev.addRole(new Role(RoleType.Admin));
			admin.addRole(new Role(RoleType.Admin));
			normalUser.addRole(new Role(RoleType.User));

			userRepository.save(dev);
			userRepository.save(admin);
			userRepository.save(normalUser);

			Comic comic = new Comic("Batman: The Dark Knight Returns","Batman: The Dark Knight Returns is a groundbreaking comic series by Frank Miller, Klaus Janson, and Lynn Varley. Set in a dystopian future, it follows a retired Bruce Wayne who returns as Batman to combat rising crime in Gotham City. Faced with old enemies, a corrupt system, and a volatile society, the aging Dark Knight wages a brutal war for justice. Known for its gritty narrative, complex themes, and iconic artwork, the series redefined Batman and reshaped the superhero genre, becoming one of the most influential comics of all time.","Frank Miller","DC", LocalDate.now(),"TDKR.jpg", 10.99,4,List.of(Genres.Crime,Genres.Action,Genres.Drama));
			Comic comic2 = new Comic("Superman: For All Seasons", "Superman: For All Seasons is a four-issue comic series by Jeph Loeb and Tim Sale that explores Superman's early years in Smallville and Metropolis. Told through the perspectives of key people in Clark Kent's life, it delves into his struggles with identity, responsibility, and heroism. With its introspective storytelling and evocative, Americana-inspired artwork, the series presents a heartfelt and timeless portrayal of Superman's journey from farm boy to Earth's greatest protector.", "Jeph Loeb", "DC", LocalDate.now(),"FAS.jpeg",10.99,4,List.of(Genres.Action,Genres.Drama));
			Comic comic3 = new Comic("Spider-Man: Spider-Verse", "Spider-Verse is a Marvel Comics crossover event written by Dan Slott, featuring multiple Spider-Man variants from across the multiverse. When the vampiric Inheritors begin hunting spider-powered heroes, Peter Parker must unite Spider-people like Spider-Gwen, Miles Morales, Spider-Man 2099, and many more to stop the multiversal threat. Packed with action, emotional stakes, and fan-favorite characters, Spider-Verse celebrates the rich legacy of Spider-Man while exploring themes of destiny, heroism, and family.", "Jed MacKay", "MARVEL", LocalDate.now(),"SMSV.jpg",20.99,6,List.of(Genres.Action,Genres.Drama));
			Comic comic4 = new Comic("Uzumaki","Uzumaki by Junji Ito is a Japanese horror manga that delves into the unsettling and bizarre obsession with spirals in a small coastal town called Kurouzu-cho. The story follows high schooler Kirie Goshima and her boyfriend, Shuichi Saito, as they witness the town's descent into madness. The spiral motif manifests in horrifying ways, twisting people, objects, and nature itself into grotesque forms. The narrative blends psychological horror with cosmic dread, exploring themes of obsession, transformation, and the inescapable pull of an ancient, malevolent force. Ito's masterful artwork amplifies the disturbing atmosphere, making Uzumaki a haunting and unforgettable read.", "Junji Ito", "Viz Media", LocalDate.now(),"UZU.jpg", 10.99, 3, List.of(Genres.Horror,Genres.Manga,Genres.Mystery));
			Comic comic5 = new Comic("Wonder Woman: Paradise Lost","Wonder Woman: Paradise Lost is a compelling storyline that delves into the Amazonian civil war threatening to destroy Themyscira. The collection explores Wonder Woman's struggle to navigate her duties as a warrior and diplomat amidst the chaos. Alongside this, it features key interactions with Gotham's protectors—Batman, Nightwing, and Robin—as mythological forces wreak havoc in their city. The narrative also touches on Wonder Woman's humanity through a day spent with journalist Lois Lane, providing a multifaceted view of her character.","J.M. DeMatteis","DC",LocalDate.now(),"WWPL.jpg",10.99,7,List.of(Genres.War, Genres.Drama, Genres.Action));
			Comic comic6 = new Comic("The Flash: Flashpoint","Flashpoint is a pivotal DC Comics storyline where Barry Allen (The Flash) wakes up in an altered timeline where the Justice League doesn’t exist, Bruce Wayne is dead, and a war rages between Aquaman's Atlantis and Wonder Woman's Themyscira. As Barry uncovers the truth, he learns his attempt to save his mother disrupted reality. To restore the timeline, he must face heartbreaking choices, ultimately leading to the creation of the New 52 universe.","Geoff Jones","DC",LocalDate.now(),"FFP.jpeg",10.99,5,List.of(Genres.Action,Genres.Drama,Genres.War));
			Comic comic7 = new Comic("Katana","The Katana comics delve into the life of Tatsu Yamashiro, a fierce warrior wielding the Soultaker sword, a mystical weapon that traps the souls of those it slays. Her solo series explores themes of vengeance, redemption, and personal growth as she navigates the challenges of her past while seeking justice. In the 2013 solo series, Katana ventures to a Japanese town steeped in mysticism and crime, where she confronts the Yakuza and uncovers secrets about her weapon and her destiny. The stories emphasize her resilience, tactical prowess, and complex relationships with allies and enemies alike.","Anne Nocenti","DC",LocalDate.now(),"KTA.jpg",10.99,5,List.of(Genres.Drama,Genres.Action,Genres.Crime));
			Comic comic8 = new Comic("Constantine","The 2013 Constantine comic series follows John Constantine, a master of the occult and anti-hero, as he navigates the dark, supernatural underworld. Known for his wit and cunning, Constantine battles malevolent forces, deals with demons, and uses magic to solve dangerous and mysterious crises. The series combines horror, mysticism, and dark fantasy, capturing Constantine’s complex personality and his unyielding fight against evil.","Ray Fawkes","DC",LocalDate.now(),"COS.jpg",10.99,24,List.of(Genres.Action, Genres.Mystery, Genres.Romance));
			Comic comic9 = new Comic("Ghost Rider","The Ghost Rider comics follow Johnny Blaze and other hosts as they transform into the vengeful Spirit of Vengeance, battling demons, supernatural enemies, and their own inner demons. The series blends dark horror, supernatural powers, and action-packed stories, exploring themes of redemption, justice, and the curse of being a hellbound warrior. Ghost Rider's iconic skull and fiery abilities make him a unique and powerful force in the Marvel Universe.","Ed Brisson","MARVEL",LocalDate.now(),"GR.jpg",10.99,6,List.of(Genres.Action,Genres.Horror,Genres.Mystery));
			Comic comic10 = new Comic("Wolverine: Madripoor Knights","Wolverine: Madripoor Knights is a four-issue mini-series published in 2009. The story takes place in the seedy, crime-ridden city of Madripoor, where Wolverine confronts a web of corruption, dangerous enemies, and his own dark past. The series combines action, espionage, and gritty street-level storytelling, showcasing Wolverine's brutal and tactical approach to justice.This book sees the three heroes team up to battle the Hand in Madripoor. What makes it even better is that it's written by Uncanny X-Men legend Chris Claremont, who wrote the original issue.","Chris Claremont","MARVEL",LocalDate.now(),"WMK.jpg",10.99,4,List.of(Genres.Action,Genres.Crime));
			Comic comic11 = new Comic("Spider-Gwen: The Ghost Spider","Spider-Gwen's popularity has skyrocketed over the years. Part of that is her place in the Spider-Verse movies, with Marvel and Disney also putting her everywhere they can to take advantage of that. Spider-Gwen has had several ongoing series over the years, but they usually occur in her own universe - Earth-65. However, with the character bigger than ever, Marvel has pulled a Miles Morales with her and brought her to the main Marvel Universe. Spider-Gwen: The Ghost Spider is the first issue in a new era for the spider-powered Gwen Stacy. Spider-Gwen has a whole new universe in front of her.","Seanan McGuire","MARVEL",LocalDate.now(),"SGGS.jpg",20.99,21,List.of(Genres.Romance,Genres.Action, Genres.Comedy));
			Comic comic12 = new Comic("Daredevil","The 2023 Daredevil series, written by Chip Zdarsky, focuses on Matt Murdock as he navigates the challenges of being both a lawyer and the vigilante Daredevil. The series delves into Matt's complex personal struggles, his battle against crime in Hell’s Kitchen, and his evolving role in the superhero community. With intense action, moral dilemmas, and deep character development, it explores themes of justice, redemption, and the blurred lines between heroism and the law.","Chip Zdarsky","MARVEL",LocalDate.now(),"DDV.jpg",25.99,15,List.of(Genres.Action, Genres.Crime, Genres.Drama));
			Comic comic13 = new Comic("Blade","The 2011 Blade comic series follows the half-vampire, half-human Daywalker as he continues his battle against vampires and supernatural threats. In this series, Blade faces powerful enemies, including vampire factions and dark occult forces, while grappling with his own inner struggles as a hybrid. The story combines Blade’s brutal fighting style with a gritty, supernatural noir atmosphere, delivering intense action and dark, supernatural storytelling.","Tim Seeley","MARVEL",LocalDate.now(),"BL.jpg",15.99,6,List.of(Genres.Horror, Genres.Action, Genres.Mystery));
			Comic comic14 = new Comic("Star Wars: Kanan - The Last Padawan","Star Wars: Kanan – The Last Padawan follows the journey of Kanan Jarrus, a Jedi survivor of Order 66, during the height of the Clone Wars. The series delves into his early life as a Padawan under Jedi Knight Depa Billaba, his struggles to survive after the fall of the Jedi Order, and his transition into the self-reliant and resourceful leader of the Rebel crew in Star Wars Rebels. The story highlights Kanan’s growth from a young Jedi into the mentor figure we see in later Star Wars timelines, while exploring themes of loss, survival, and self-discovery.","Greg Weisman","MARVEL",LocalDate.now(),"SWK.jpg",20.99,12,List.of(Genres.Sci_Fi, Genres.War, Genres.Action));
			Comic comic15 = new Comic("Star Wars: Darth Vader","Star Wars: Darth Vader (2015) is a Marvel Comics series written by Kieron Gillen and illustrated by Salvador Larroca. This series picks up right after the events of Star Wars: Episode IV – A New Hope, focusing on Darth Vader’s journey as he continues to enforce the Empire’s will and seeks revenge against those who oppose him. The series explores Vader’s struggles with his identity as both a Sith Lord and a former Jedi, as well as his relationship with Emperor Palpatine and his hunt for the Rebel Alliance.","Kieron Gillen","MARVEL",LocalDate.now(),"SWDV.jpg",25.99,25,List.of(Genres.Sci_Fi,Genres.War,Genres.Action));
			Comic comic16 = new Comic("Star Wars: Princess Leia","Star Wars: Princess Leia is a Marvel Comics limited series written by Mark Waid and illustrated by Terry Dodson. The series focuses on Princess Leia Organa in the aftermath of Star Wars: Episode IV – A New Hope. In this story, Leia embarks on a mission to save the citizens of her home planet, Alderaan, who are stranded in the aftermath of its destruction. Along the way, she confronts the emotional weight of her past and her role as a leader of the Rebel Alliance, while navigating a hostile galaxy. The series highlights her strength, compassion, and determination in the face of adversity.","Mark Waid","MARVEL",LocalDate.now(),"SWPL.jpg",20.99,5,List.of(Genres.Sci_Fi, Genres.War, Genres.Action));
			Comic comic17 = new Comic("Star Wars: Bounty Hunters","Star Wars: Bounty Hunters is a Marvel Comics series that first launched in June 2020. Written by Ethan Sacks and illustrated by Paolo Villanelli, the series focuses on a diverse group of bounty hunters operating in the galaxy during the reign of the Galactic Empire. The story follows familiar characters such as Boba Fett, Bossk, Valance, and others as they navigate dangerous missions and rivalries while dealing with the constant threat of the Empire and other factions. The series explores the darker side of the galaxy, the competitive world of bounty hunting, and the moral dilemmas faced by its characters.","Ethan Sacks","MARVEL",LocalDate.now(),"SWBH.jpeg",20.99,27,List.of(Genres.Sci_Fi, Genres.War, Genres.Action));
			Comic comic18 = new Comic("Star Wars: Mara Jade","Mara Jade: By the Emperor's Hand is a Star Wars Legends comic miniseries published by Dark Horse Comics. The series was written by Kevin J. Anderson and illustrated by Dario Carrasco Jr. It delves into the backstory of Mara Jade, focusing on her role as the Emperor's Hand—a highly trained assassin and enforcer for Emperor Palpatine during the early years of the Empire. The story follows Mara Jade's journey from her upbringing as a child on the Sith homeworld, her training in the Emperor’s service, and her development into one of the most feared agents in the galaxy. It provides insight into her complex relationship with the Emperor and her eventual transformation into a more independent figure after his death.","Kevin J. Anderson","MARVEL",LocalDate.now(),"SWMJ.jpg",20.99,5,List.of(Genres.Sci_Fi, Genres.War, Genres.Drama));
			Comic comic19 = new Comic("Star Wars: Galaxy's Edge","Star Wars: Galaxy’s Edge is a Marvel Comics miniseries that ties into the Star Wars theme park experience at Disneyland and Disney World, specifically inspired by the Star Wars: Galaxy's Edge attraction. The series is written by Ethan Sacks, with art by Will Sliney, and it follows a new original storyline featuring Ohnaka, a pirate captain, as well as familiar characters like Chewbacca and Rey. The story takes place in the remote outpost of Batuu, a key location within the Star Wars universe that serves as the backdrop for the Galaxy’s Edge attractions.","Ethan Sacks","MARVEL",LocalDate.now(),"SWGE.jpg",25.99,5,List.of(Genres.Sci_Fi, Genres.War, Genres.Action));
			Comic comic20 = new Comic("Invincible","Invincible is a superhero comic series created by Robert Kirkman, Cory Walker, and Ryan Ottley, published by Image Comics. It follows Mark Grayson, a seemingly ordinary teenager who discovers he has inherited superpowers from his father, Omni-Man, Earth's most powerful superhero. Adopting the name \"Invincible,\" Mark navigates the challenges of balancing a normal life with his responsibilities as a hero, only to uncover shocking truths about his father and their alien heritage.","Robert Kirkman","Image Comics",LocalDate.now(),"INV.jpg",15.99,144,List.of(Genres.Action,Genres.Drama,Genres.Comedy));
			Comic comic21 = new Comic("The Boys","The Boys is a dark, satirical comic series set in a world where superheroes, known as \"supes,\" are not the noble figures they're made out to be. Instead, they are corrupt, reckless, and controlled by the powerful corporation Vought International. The story follows a black-ops team, \"The Boys,\" led by the ruthless Billy Butcher, tasked with keeping the supes in check—by any means necessary. Joined by Hughie Campbell, a man with a personal vendetta against the supes, the team exposes the dark side of heroism in a brutal, action-packed narrative that critiques celebrity culture, corporate greed, and unchecked power.","Garth Ennis","Dynamite Entertainment",LocalDate.now(),"TB.jpg",10.99,72,List.of(Genres.Action,Genres.Comedy,Genres.Crime));
			Comic comic22 = new Comic("The Crow","The Crow is a gothic revenge story written and illustrated by James O'Barr. It follows Eric Draven, a young man who is brutally murdered alongside his fiancée, Shelly, by a gang of criminals. One year later, Eric is resurrected by a supernatural crow, granting him the power to exact vengeance on those responsible for their deaths. Set in a bleak, rain-soaked city, the comic explores themes of love, loss, and justice, blending raw emotion with haunting visuals. Known for its poetic tone and stark black-and-white artwork, The Crow has become a cult classic, resonating deeply with readers drawn to its tragic beauty and unrelenting intensity.","James O'Barr","Caliber Press",LocalDate.now(),"CRO.jpg",15.99,5,List.of(Genres.Drama,Genres.Horror,Genres.Crime));
			Comic comic23 = new Comic("Something is Killing the Children","Something is Killing the Children is a horror comic series written by James Tynion IV with art by Werther Dell'Edera. The story follows Erica Slaughter, a mysterious and stoic monster hunter who belongs to a secretive organization called the Order of St. George. Her mission is to protect towns plagued by terrifying creatures that prey on children—monsters that only kids can see. As Erica fights to save lives, she also battles the organization's dark secrets and her own haunted past. The series is known for its gripping storytelling, atmospheric art, and exploration of fear, trauma, and resilience.","James Tynion IV","BOOM! Studios",LocalDate.now(),"SIKC.jpg",25.99,40,List.of(Genres.Horror,Genres.Drama,Genres.Action));
			Comic comic24 = new Comic("The Silver Coin","The Silver Coin is a horror anthology comic series published by Image Comics, created by Michael Walsh. Each issue tells a standalone, chilling story connected by a mysterious, cursed silver coin. This malevolent artifact brings darkness, suffering, and supernatural consequences to those who possess it, exploring themes of greed, desperation, and the human condition. The series features a rotating cast of talented writers, including Chip Zdarsky, Kelly Thompson, Ed Brisson, and more, ensuring a diverse range of horror stories that span different genres and eras. Walsh’s haunting art style adds to the eerie and atmospheric tone of each tale, making The Silver Coin a gripping and unsettling read for horror enthusiasts.","Michael Walsh","Image Comics",LocalDate.now(),"SLC.jpg",15.99,15,List.of(Genres.Horror, Genres.Mystery, Genres.Drama));
			Comic comic25 = new Comic("The Sandman", "The Sandman is a critically acclaimed dark fantasy comic series written by Neil Gaiman, published by DC Comics under the Vertigo imprint. The story revolves around Morpheus, also known as Dream or Sandman, who governs the world of dreams. When captured by a group of occultists, Dream finds himself trapped in a nightmare realm for over a century, leading to a series of events that reshape both the waking and dream worlds. The series blends mythology, fantasy, horror, and psychological storytelling, exploring themes of identity, destiny, and the power of imagination. Known for its richly developed characters, intricate plots, and haunting visuals, The Sandman has become a seminal work in graphic literature, influencing a wide range of media and genres.","Neil Gaiman","DC",LocalDate.now(),"SDM.jpg",20.99,75,List.of(Genres.Horror,Genres.Mystery,Genres.Drama));
			Comic comic26 = new Comic("One-Punch Man","One Punch Man is a Japanese superhero series that follows the story of Saitama, an unassuming man who becomes a hero for fun. Despite his plain appearance and laid-back attitude, Saitama possesses unparalleled strength, capable of defeating any enemy with a single punch. However, his immense power leaves him bored and unfulfilled as he searches for a worthy opponent. Blending intense action with sharp humor and satire, the series explores themes of heroism, purpose, and the struggles of an overpowered protagonist in a chaotic world of heroes and monsters.","ONE","Viz Media",LocalDate.now(),"OPM.jpg",5.99,210,List.of(Genres.Action,Genres.Comedy,Genres.Manga));
			Comic comic27 = new Comic("Spy X Family","The story follows Loid Forger, an elite spy code-named \"Twilight,\" tasked with a top-secret mission to infiltrate an elite school and get close to a high-ranking official. To do so, he must create a fake family. Loid adopts a young girl named Anya, who secretly has telepathic abilities, and enters a sham marriage with Yor, an unassuming woman who is, unbeknownst to him, a deadly assassin. None of them know each other's true identities, leading to comedic and heartwarming scenarios. ","Tatsuya Endo","Viz Media",LocalDate.now(),"SXF.png",10.99,108,List.of(Genres.Action,Genres.Comedy,Genres.Manga));
			Comic comic28 = new Comic("Star Wars: Han Solo","Star Wars: Han Solo is a five-issue limited comic series published by Marvel Comics in 2016. Written by Marjorie Liu and featuring art by Mark Brooks, the series explores Han Solo’s adventures between A New Hope and The Empire Strikes Back, providing insight into his past as a smuggler and his rise as a key player in the Rebel Alliance. The story follows Han Solo as he participates in the prestigious Dragon Void Run, a dangerous starship race that attracts some of the best pilots in the galaxy. Alongside his loyal co-pilot, Chewbacca, Han navigates treacherous competitors, deadly rivalries, and complex missions for the Rebel Alliance. Throughout the race, Han must balance his reputation as a reckless smuggler with his growing responsibilities as a hero fighting against the Empire.","Marjorie Liu","MARVEL",LocalDate.now(),"SWHS.jpg",20.99,5,List.of(Genres.Sci_Fi,Genres.War,Genres.Action));
			Comic comic29 = new Comic("Star Wars: Obi-Wan & Anakin","Star Wars: Obi-Wan & Anakin is a four-issue comic miniseries published by Marvel Comics in 2015. Written by Charles Soule with art by Marco Checchetto, the series explores the early years of the Jedi Master Obi-Wan Kenobi and his Padawan, Anakin Skywalker, during the height of the Clone Wars. Set between Episode I: The Phantom Menace and Episode II: Attack of the Clones, the series follows Obi-Wan and Anakin as they undertake a mission to protect a peaceful farming world, Pijal, from separatist forces. However, their mission becomes increasingly complicated as tensions between the Jedi and the local populace rise, and Anakin’s impatience and emotional instability begin to threaten their mission’s success.","Charles Soule","MARVEL",LocalDate.now(),"SWOWA.jpg",20.99,4,List.of(Genres.Sci_Fi,Genres.War,Genres.Action));
			Comic comic30 = new Comic("Star Wars: Vader Down","The storyline picks up after the events of The Empire Strikes Back, where Vader leads a brutal campaign against the Rebel Alliance to eliminate any remaining resistance. During a mission to capture Princess Leia, Vader finds himself stranded on a remote Rebel-held planet, Vrogas Vas, after his ship is destroyed in battle. The Rebels, led by Luke Skywalker and his friends, face a desperate battle to survive against Vader’s overwhelming force, as they try to protect Leia and rally reinforcements to rescue them.","Kieron Gillen","MARVEL",LocalDate.now(),"SWVD.jpg",20.99,5,List.of(Genres.Sci_Fi,Genres.War,Genres.Action));

			comicRepository.save(comic);
			comicRepository.save(comic2);
			comicRepository.save(comic3);
			comicRepository.save(comic4);
			comicRepository.save(comic5);
			comicRepository.save(comic6);
			comicRepository.save(comic7);
			comicRepository.save(comic8);
			comicRepository.save(comic9);
			comicRepository.save(comic10);
			comicRepository.save(comic11);
			comicRepository.save(comic12);
			comicRepository.save(comic13);
			comicRepository.save(comic14);
			comicRepository.save(comic15);
			comicRepository.save(comic16);
			comicRepository.save(comic17);
			comicRepository.save(comic18);
			comicRepository.save(comic19);
			comicRepository.save(comic20);
			comicRepository.save(comic21);
			comicRepository.save(comic22);
			comicRepository.save(comic23);
			comicRepository.save(comic24);
			comicRepository.save(comic25);
			comicRepository.save(comic26);
			comicRepository.save(comic27);
			comicRepository.save(comic28);
			comicRepository.save(comic29);
			comicRepository.save(comic30);
		};
	}


	public static void main(String[] args) {
		SpringApplication.run(ComicsRestApplication.class, args);
	}

}
